' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
title Logging context in Safe-Posix-Platform (SPP)
frame SPP {

  frame "Adaptive AUTOSAR CPU" {
      node Application1
      node Application2
      node SystemApplication
      node "Logging framework" as DataRouter
      boundary "UDP multicast" as UDP

      Application1 ..> DataRouter : LOG()
      Application2 ..> DataRouter : TRACE()
      SystemApplication ..> DataRouter : LOG()
      DataRouter ..> UDP: DLT
  }
}

node Logger

UDP ==> Logger

@enduml
