@startuml context-highlevel

frame "ECU" {
  node AdaptiveApplication {
    component ApplicationLogic
    interface "mw::log" as mwlog1
    component "mw::log implementation" as mwlog1_impl

    mwlog1 - mwlog1_impl
    ApplicationLogic --> mwlog1 : verbose
    ApplicationLogic --> mwlog1 : non-verbose

  }
  note right of AdaptiveApplication
    EV Application,
    e.g., RoadModel
  end note



  node SystemApplication {
    component SystemApplicationLogic
    interface "mw::log" as mwlog2
    component "mw::log implementation" as mwlog2_impl

    mwlog2 - mwlog2_impl
    SystemApplicationLogic --> mwlog2 : verbose
  }
  note right of SystemApplication
    e.g. StartupApp
  end note


  node Datarouter {
  }
  note right of Datarouter
    DLT logging daemon
  end note
}

boundary "UDP Multicast" as udp

mwlog1_impl --> Datarouter : write
mwlog2_impl --> Datarouter : write

Datarouter --> udp: "send DLT messages:"


@enduml
