' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

node AdaptiveApplication {
    component "Application" as app
}

node "Datarouter" {
  component "Message Server" as msg_server
  component [Source Session] as sourcesession
  component UnixDomainServer
}

node "DatarouterConf" {
  component UnixDomainClient as config_client
}

queue "SourceBuffer: MWSR buffer" as RB1
note top of RB1
  Shared memory
  allocated by Application
end note

app -> msg_server : connect()
config_client -> UnixDomainServer : connect()

app .> RB1 : create()
app -> RB1 : write()

RB1 <- sourcesession : read()
msg_server ..> sourcesession: create()

@enduml
