@startuml

title mw::log Packages

package mw {
  package log {
    enum LogLevel {
      + kOff
      + kFatal
      + kError
      + kWarn
      + kInfo
      + kDebug
      + kVerbose
    }

    enum LogMode {
      + kOff,
      + kConsole,
      + kRemote,
      + kFile,
      + kInvalid
    }

    enum LogManager::ClientState {
        kNotConnected,
        kConnected,
        kUnknown
    }

    class LogManager {
      + CreateLogContext(const mw::core::StringView&, const mw::core::StringView&, const LogLevel) : Logger&
      + defaultLogContext() : Logger&
      + static instance() : LogManager&
      - FindExistingLogger(const mw::core::StringView&) : score::cpp::optional<std::reference_wrapper<Logger>>
      - InsertNewLogger(const mw::core::StringView&, const mw::core::StringView&, const LogLevel) : Logger&
    }

    class Logger {
        + Logger(context: std::string_view)
        + LogFatal() : LogStream
        + LogError() : LogStream
        + LogWarn() : LogStream
        + LogInfo() : LogStream
        + LogDebug() : LogStream
        + LogVerbose() : LogStream
        + WithLevel(const LogLevel) : LogStream
        + IsLogEnabled(const LogLevel) : bool
        + IsEnabled(const LogLevel) : bool
        + GetContext() : std::string_view
        - context_ : LoggingIdentifier
    }

    class LogStream {
        + LogStream(LogLevel, core::StringView) noexcept
        + LogStream(core::StringView, LogLevel) noexcept
        + ~LogStream() noexcept

        + LogStream(const LogStream&) = delete
        + LogStream& operator=(const LogStream&) = delete
        + LogStream(LogStream&&) noexcept
        + LogStream& operator=(LogStream&&) = delete

        + void Destruct() noexcept
        + void Flush() noexcept
        + LogStream& WithLocation(core::StringView, int) noexcept

        + LogStream& operator<<(bool) noexcept
        + LogStream& operator<<(uint8_t) noexcept
        + LogStream& operator<<(uint16_t) noexcept
        + LogStream& operator<<(uint32_t) noexcept
        + LogStream& operator<<(uint64_t) noexcept
        + LogStream& operator<<(int8_t) noexcept
        + LogStream& operator<<(int16_t) noexcept
        + LogStream& operator<<(int32_t) noexcept
        + LogStream& operator<<(int64_t) noexcept
        + LogStream& operator<<(float) noexcept
        + LogStream& operator<<(double) noexcept
        + LogStream& operator<<(const char* const) noexcept
        + LogStream& operator<<(const LogRawBuffer&) noexcept
        + LogStream& operator<<(const LogHex8&) noexcept
        + LogStream& operator<<(const LogHex16&) noexcept
        + LogStream& operator<<(const LogHex32&) noexcept
        + LogStream& operator<<(const LogHex64&) noexcept
        + LogStream& operator<<(const LogBin8&) noexcept
        + LogStream& operator<<(const LogBin16&) noexcept
        + LogStream& operator<<(const LogBin32&) noexcept
        + LogStream& operator<<(const LogBin64&) noexcept
        + LogStream& operator<<(const core::StringView) noexcept
        + LogStream& operator<<(const std::thread::id&) noexcept

        + LogStream& Arg<T>(const T&) noexcept
        + LogStream& Arg<T>(core::StringView, const T&) noexcept
        + LogStream& Arg<T>(core::StringView, const T&, core::StringView) noexcept
        + LogStream& operator<<(const Argument<T>&) noexcept

        + static constexpr kBmwLogStreamBufferSize : size_t
        - std::array<std::uint64_t, kBmwLogStreamBufferSize> pre_allocated_buffer_
        - template <typename T> LogStream& LogWithMiddleWare(T&&)
    }

  }

}

@enduml
