@startuml

title ara::log implementation with TRACE_X macros
participant UserFunction as fun
participant "ara::log::LogManager" as lm
participant "ara::log::Logger" as logger
participant "ara::log::LogStream" as ls
participant LogContextData
participant TRACE_MACRO as tm

group First request for specific logger
fun -> lm++ : CreateLogger()
lm -> logger++: Logger()
logger --> lm--
lm --> fun-- : Logger&
end

group Subsequent requests for specific logger
fun -> lm++ : CreateLogger()
lm --> fun-- : Logger&
end

fun -> logger++: LogInfo()
logger -> ls*: LogStream(Logger, logLevel=kInfo)
activate ls
ls -> LogContextData*: LogContextData()
activate LogContextData
LogContextData --> ls --
ls -> LogContextData ++: log_start(logLeverl=kInfo)
LogContextData --> ls --

ls --> logger --
logger -->fun--

fun -> ls++: << (double d)
ls -> LogContextData++: log_double(d)
LogContextData --> ls--
fun <-- ls--

logger -> ls++: << (string s)
ls -> LogContextData++: log_string(s)
LogContextData --> ls--
fun <-- ls--

logger -> ls++: << (int32_t i)
ls -> LogContextData++: log_string(s)
LogContextData --> ls--
fun <-- ls--
fun ->ls++: ~LogStream()
ls -> LogContextData++: log_flush()

LogContextData -> tm++: TRACE_INFO(LogContextData.logEntry)
tm --> LogContextData--
LogContextData --> ls
destroy LogContextData
logger <-- ls--
destroy ls

fun <-- logger--
@enduml
