# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("//score/test/component:defs.bzl", "py_logging_itf_test")

py_logging_itf_test(
    name = "test_datarouter_scenarios",
    srcs = ["test_datarouter_scenarios.py"],
    filesystem = "//score/test/component/dlt_generator_app:dlt_generator_filesystem",
)
