# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "model",
    srcs = [
        "datarouter.fcdl",
        "//platform/aas/intc/lifecycle_state_machine/adaptive_model/interfaces:machinefgstate_interface",
        "//score/datarouter/model/interface:persistency",
    ],
    visibility = [
        "//pqr/abc/abc-lmn/config/common/pas/datarouter:__subpackages__",
        # "@xyz//pqr/abc/abc-lmn/config/common/pas/datarouter:__subpackages__",
    ],
)
