@startuml "Remote Logging High-level Overview"

skinparam linetype ortho

skinparam component {
  BackgroundColor<<score_baselibs>> #E8F4FA
  BackgroundColor<<score_logging>> #FDEBD0
}
skinparam node {
  BackgroundColor<<score_logging>> #FDEBD0
}

frame "ECU" {
  together {
    node FeatureApplication <<ASIL B>> {
      component ApplicationLogic
      package "mw::log lib" as lt1 {
        component "Frontend API\n(Logger, LogStream, TRACE)" as lt1_frontend <<score_baselibs>>
        component "Remote Backend" as lt1_backend <<score_logging>> {
          component "/dev/shmem/fa_*" as shmem_fa <<memory,shared>>
        }
        lt1_frontend ..> lt1_backend : registers as\nbackend/recorder
      }

      ApplicationLogic --> lt1_frontend : verbose <<mw::log API>>
      ApplicationLogic --> lt1_frontend : non-verbose <<TRACE API>>
    }

    node SystemApplication <<ASIL B>> {
      component SystemApplicationLogic
      package "mw::log lib" as lt2 {
        component "Frontend API\n(Logger, LogStream, TRACE)" as lt2_frontend <<score_baselibs>>
        component "Remote Backend" as lt2_backend <<score_logging>> {
          component "/dev/shmem/sa_*" as shmem_sa <<memory,shared>>
        }
        lt2_frontend ..> lt2_backend : registers as\nbackend/recorder
      }

      SystemApplicationLogic --> lt2_frontend : verbose <<mw::log API>>
    }
  }
  note top of SystemApplication
    E.g.: StartupManager, etc.
  end note


  node Datarouter <<ASIL QM>> <<score_logging>> {
    node SourceSession1 {
    }
    node SourceSession2 {
    }
  }

  package "Operating System" {
    node NetworkStack <<ASIL QM>> {

    }
  }
}

lt1_backend ..> shmem_fa : write
lt2_backend ..> shmem_sa : write

shmem_fa <.. Datarouter : read
shmem_sa <.. Datarouter : read

FeatureApplication -[hidden]right-> SystemApplication
FeatureApplication -[hidden]down-> Datarouter
SystemApplication -[hidden]down-> Datarouter
lt1_backend -[hidden]down-> SourceSession1
lt2_backend -[hidden]down-> SourceSession2

lt1_backend <-0)-> SourceSession1 : message_passing
lt2_backend <-0)-> SourceSession2 : message_passing

Datarouter -(0-> NetworkStack: socket
NetworkStack -r-> Multicast: sends multicast

legend right
  |Color| Repository | Contents |
  |<#E8F4FA>| **score_baselibs** | mw::log frontend API (Logger, LogStream, TRACE) |
  |<#FDEBD0>| **score_logging** | mw::log remote backend (shmem writer) + datarouter daemon |
endlegend

@enduml
